### ISSUE TITLE
Rename instruction from `cal` to `oeis`

### ISSUE THREAD

**Issue by neoneye** [ckrause/loda#103]
This will break with the current 3 letter instruction convention. Lots of programs will have to be updated.

For future LODA people it may be more obvious that it's related to OEIS. It wasn't intuitive for me.

**Comment by ckrause** [comment]
An alternative could be to use paths as argument for `cal` operation. So instead of `cal $0,12345` we would write `cal $0,'../012/A012345.asm'`. The disadvantage would be that we would need to allow strings as arguments and we cannot easily access the numeric sequence ID anymore.

**Comment by neoneye** [comment]
I have been thinking about this for 2 days now. I think the highest priority is optimizing the performance of the miner.

Adding paths will make parsing more complex, the parse tree will have to deal with more edge cases, the memory foot print will go up, and it may be more time consuming to verify if a program is correctly linked with its dependencies. It can maybe be a separate instruction, but I don't think it should be the same instruction. Simplicity. A separate instruction can be introduced in the future for this.

Using an integer for representing oeis has many benefits.
Either use a `bitset` with 350000 oeis entries takes up 44kb of memory. Or use an `unordered_set` with a 32 bit key with 30000 loda entries takes up +120kb of memory.

**Comment by ckrause** [comment]
Another option: rename it to `seq` (for "sequence").

**Comment by neoneye** [comment]
`seq` is great.

Various 3 letter names:
```
run $1,12345  ; run
exe $1,12345  ; exe'cute
fun $1,12345  ; fun'ction
eva $1,12345  ; eva'luate
pro $1,12345  ; pro'gram
cal $1,12345  ; call or cal'culate
seq $1,12345  ; seq'uence
eis $1,12345  ; oeis, without the online prefix.
```

**Comment by ckrause** [comment]
Renamed it to `seq`. It will take some time until all programs will be updated by the maintenance job. For backward compatibility `cal` is still supported.
