### ISSUE TITLE
Eval modes for rational and irrational numbers

### ISSUE THREAD

**Issue by ckrause** [ckrause/loda#113]
Support alternative `eval` modes:

## (1) Rational Number Sequences

Use `$0` as input. Two output cells: `$1` is the numerator and `$2` is the denominator. So we can evaluate a program to a sequence of rationals.

## (2) Irrational Numbers 

(2.1) Use (1) to generate a sequence of rationals. Then sum up all terms and take the limit.  Convergence not guaranteed.

(2.2) Use (1) to generate two sequences `a(n)` and `b(n)`. Use these two sequences in a continued fraction (cf. http://www.ramanujanmachine.com/ ).

In theory we should be able to do mining for irrational numbers, like roots, e, pi, and zeros of the Riemann zeta function: http://www.dtc.umn.edu/~odlyzko/zeta_tables/index.html

**Comment by ckrause** [comment]
See also https://sites.math.washington.edu/~morrow/336_10/papers/shawn.pdf

**Comment by neoneye** [comment]
Interesting idea.
