### ISSUE TITLE
Use `$0` for output register

### ISSUE THREAD

**Issue by neoneye** [ckrause/loda#139]
Currently `$1` is the output register.

It will affect all programs. 

Multiple outputs: What if someday a second output value is to be returned (rational number, complex number, coordinates). Should it then be placed in `$2`. Or some other day, what if 3 output values are to be returned (3d vector).

Multiple inputs: It would be nice with programs that takes multiple inputs such as bitwise operators. So if the input goes into `$0, $1`. Then it it's awkward that the output is in the `$1` register.

I think `$0` for output, is consistent and future proof.

**Comment by ckrause** [comment]
I already made some preparations a while ago to make this configurable, but there are still some issues in the miner. I'm not fully sure if we should change it. We will need to inject a `mov $0,$1` at the end of all programs.

**Comment by neoneye** [comment]
Indeed, impacts all programs.

**Comment by ckrause** [comment]
done
