### ISSUE TITLE
Semantics of binomial coefficient

### ISSUE THREAD

**Issue by ckrause** [ckrause/loda#140]
The `bin` operation currently supports negative arguments based on the paper by Kronenburg: https://arxiv.org/pdf/1105.3689.pdf

The advantage is that the miner has a higher chance of finding a working and useful program with `bin`. On the other hand, the extension to negative arguments is not really trivial and sometimes the miner generates programs where negative arguments are used, but actually "normal" (positive) arguments would also work.

Should we disable negative arguments for `bin` and throw an error in that case? This would mean that some programs become invalid and need to be regenerated.

**Comment by neoneye** [comment]
Disabling negative parameters makes good sense with me.

If programs with 2 parameters some day becomes possible, then there can be a binomial program that supports negative parameters. Then the `bin` instruction can be only for the positive parameters.

The `bin` instruction counts as 1 eval step, even though it can be heavy to compute. 
It takes cpu cycles dealing with the edge cases.

**Comment by ckrause** [comment]
Wolfram Alpha also supports negative args for binomial. So I think it makes sense to keep it.
