### ISSUE TITLE
Support for Gaussian Integers

### ISSUE THREAD

**Issue by ckrause** [ckrause/loda#39]
LODA programs currently operate on signed integers (datatype `number_t`). The expressiveness could be expanded by considering Gaussian Integers instead. This would mean we have a real and an imaginary part and extend the semantics of all existing operations to the domain.

An overview of relevant aspects of Gaussian Integers can be found, e.g., in the tutorial bei Keith Conrad: https://kconrad.math.uconn.edu/math5230f12/handouts/Zinotes.pdf

**Comment by karttu** [comment]
Bitwise-operators XOR, OR, AND would very much be useful for the myriad of binary buff sequences in OEIS. (Or if we were minimalist purists, then just NAND would suffice?) But of course, the set of built-in primitives greatly affects which particular subset of sequences Lodaminer will home to.

**Comment by ckrause** [comment]
This would have a high impact/effort on all aspects of LODA. I mainly put it here to be open for such extensions, but I don't think we will go in this direction in the near future.

**Comment by karttu** [comment]
I would also say that it would have quite a small (positive) effect whenmatching OEIS sequences. See e.g., https://oeis.org/search?q=gaussian&language=english&go=Search
