### ISSUE TITLE
Question about minimizer's recommended deletions inside the loop.

### ISSUE THREAD

**Issue by karttu** [ckrause/loda#46]
(This is more a question than issue, but you could also read it as a request for a better documentation of the execution model...)

Recently, when I have hand-coded a few sequences in LODA, I have been told or noticed myself that the minimizer would like to get rid off certain statements in them.
For example, in https://github.com/ckrause/loda/blob/master/programs/oeis/003/A003958.asm#L25
it would like to delete those three statements in lines 25 - 27:
  mov $7,$0    ; Check whether $0 has reached one...
  cmp $7,1
  sub $8,$7    ; If so, then set $8 from 1 to 0 (to stop in the next iteration!)
and in
https://github.com/ckrause/loda/blob/master/programs/oeis/008/A008683.asm#L32
it would like to get rid off those seven instruction on lines 32 - 38, after that mul $1,$7

In A087436, it would delete that mul $4,2 on line 34:
https://github.com/ckrause/loda/blob/master/programs/oeis/087/A087436.asm#L34
which however, speeds the execution (sometimes even nearly twicefold), as in that latter loop we can safely ignore even primes, and concentrate only on finding odd ones, by incrementing the "prime-candidate register" $2 by 2 (instead of 1) at every iteration.

And in A003958 and especially in A008683, the immediate exit from the loop should speed the execution a lot in right conditions (e.g., in latter when the argument is a multiple of 4 with lots of other prime factors > 2 as well).

But, the big "but" here: Have I understood the execution model of LODA machine correctly? I mean, is there any difference to the execution time with such "loop exit hacks" ? At least it is reassuring that minimizer recognizes the results to be identical even when they were removed, which kind of proves that those optimizations are correct in the sense that they don't affect the eventual result returned.

**Comment by ckrause** [comment]
The miner checks the following conditions in order. If one of them is satisfied it updates the program.

1. does the new program compute more terms?
2. does it require less steps (aggregated) for computing the same number of terms?
