### ISSUE TITLE
Video/podcast explaining what LODA is about

### ISSUE THREAD

**Issue by neoneye** [ckrause/loda#47]
The OEIS superseeker is impressive. IIRC Niel Sloane has said that an AI enhanced superseeker would be even more awesome.

The [sequence database](http://sequencedb.net/) is also really good at derermining the formula

And in a similar way there is the [Ramanujan Machine](http://www.ramanujanmachine.com/).

I see the LODA mining code and I wonder, is this intended as an automated formula seeker?

Instead of storing the assembly code as text. Does it use a byte code representation of the instructions?

When finding a formula, is the instructions represented as a genome (similar to DNA). What kind of mutations does it do in every fitness iteration?

So many questions. Maybe a video or a podcast where you explain things.

Greetings from a fellow oeis fan.

**Comment by ckrause** [comment]
Thanks for your feedback and the questions. I've sent you an invitation to Slack. I think that's easier for discussions.

**Comment by neoneye** [comment]
Thanks. Can you send the invite to `neoneye@gmail.com`.

**Comment by karttu** [comment]
So there is not yet either such a video or a podcast? (The title lacks the question mark... but it is an excellent suggestion).

**Comment by ckrause** [comment]
No, I have been working on this project alone so far. Only recently, I felt it's time to open it and ask for contributions.
