### ISSUE TITLE
Suggested new instructions: DID ("Divide (but only) If it Divides").

### ISSUE THREAD

**Issue by karttu** [ckrause/loda#53]
Suggested new instruction: did a,b
What it would do: Divides the target by the source value, but only if the source divides the target: a:= a/b if b|a, otherwise a:=a, making the instruction in the latter case effectively a no-op.
Rationale: Would work great with the loops, where target is also used as the loop-register. Then could be used for example to divide all instances of b out of a.
Consider the current version of A000265:
https://github.com/ckrause/loda/blob/master/programs/oeis/000/A000265.asm
; A000265: Remove all factors of 2 from n; or largest odd divisor of n; or odd part of n.
; 1,1,3,1,5,3,7,1,9,5,11,3,13,7,15,1,17,9,19,5,21,11,...
add $0,1
mov $1,$0
lpb $1,1
  mov $2,$1
  bin $2,2
  gcd $1,$2
lpe

This is not bad, only three statements inside the loop. However, bin $2,2 which computes n*(n+1)/2, makes the effective upper-size limit (in the current 64-bit-limited implementation of LODA) to drop to about half, 31 bits or such. (_Please correct me if I have understood this wrongly_).
Now, with _did_-instruction, this would make just 5 statements in total, and with just one inside the loop:

add $0,1
lpb $0,1
  did $0,2
lpe
mov $1,$0

A007814 and A007949 could be implemented similarly:

add $0,1
lpb $0,1
  did $0,3
  add $1,1
lpe

Similarly, for many routines that examine the prime factorization structure of n in general, it would be very useful, and obviate in the most cases the need to separately test for the divisibility with mod-instruction.
Also, we don't yet know what creative use cases the miner would invent for the did-instruction.

**Comment by ckrause** [comment]
This looks very useful. No concerns regarding the scope, complexity or domain of this operation. In general, we can add instructions and see what the miner makes out of it. The only question is regarding the name: do you prefer `did` or maybe `dif` (divide-if..)

**Comment by karttu** [comment]
The name is up to you, dif might be better after all. Also, it could be made zero-resistant, i.e., if the divisor were zero, then it would also work as a no-op, because 0 is not a divisor of a.
