### ISSUE TITLE
Check more terms

### ISSUE THREAD

**Issue by ckrause** [ckrause/loda#62]
We currently check 250 terms to determine whether a program matches a sequence. If it contains values exceeding the 64-bit range, we truncate the sequence to be checked.

Recent tests show that there are around 60 programs up to A060000 that have incorrect terms. We should extend the check to more terms to filter out these incorrect programs.

The proposal is: we keep the existing logic for 250 terms and extend it by an additional test: we test also terms up to, say, N=1000, but with the following behavior: we discard the program if we found a difference, but we do NOT discard the program if an overflow occurs in this range.

**Comment by ckrause** [comment]
I think these two changes should actually suffice:

* Increase this constant to 1000: https://github.com/ckrause/loda/blob/master/src/oeis_sequence.cpp#L10
* In the interpreter, the `check` function would get the expected 1000-terms sequence and an additional parameter that defines the start of the range where overflows and exceptions are allowed (250): https://github.com/ckrause/loda/blob/master/src/interpreter.cpp#L429

**Comment by ckrause** [comment]
Forgot one place: in `dumpProgram` we should only print (at most) 250 terms, not 1000:
https://github.com/ckrause/loda/blob/master/src/oeis_manager.cpp#L398

**Comment by karttu** [comment]
Just a quick comment: make it at least 2000. I will later elaborate here why.

**Comment by ckrause** [comment]
That should be ok, but we'll need to do this first: https://github.com/ckrause/loda/issues/63

**Comment by ckrause** [comment]
done
